name: extension_helpers
description: "A new Flutter package project."
version: 0.1.0
homepage: https://github.com/Emge_resource/imas_mobile/extension_helpers
publish_to: none

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  date_time_format: ^2.0.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  responsive_framework: ^1.5.1
  intl: ^0.20.2
  responsive_sizer: ^3.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
